spring.application.name=spring-security-project

server.port=9090

# MySQL
spring.datasource.url=jdbc:mysql://mysql-db:3306/authentication-spring-boot
spring.datasource.username=root
spring.datasource.password=Sujit@6299

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=mysupersecretkeymysupersecretkey123456

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sujitkr@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true