spring.application.name=spring-security-project
server.port = 9090
spring.datasource.url=jdbc:mysql://localhost:3306/authentication-spring-boot
spring.datasource.username = root
spring.datasource.password = Sujit@6299
spring.show.jpa-sql = true
spring.jpa.hibernate.ddl-auto = update



#spring.security.user.name = sujit
#spring.security.user.password = Sujit@6299

#spring.security.oauth2.client.registration.github.client-id=Ov23libfw0tFsuO3aTBt
#spring.security.oauth2.client.registration.github.client-secret=48c2731de24e5e435e46f9ab57aee964366b1b96
#spring.security.oauth2.client.registration.github.scope=read:user,user:email
